# Generated by Django 2.0.6 on 2018-06-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('quickstart', '0002_auto_20180628_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Permission')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Role'),
        ),
    ]
