# Generated by Django 2.0.6 on 2018-06-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20180629_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role_permission',
            name='permission_name',
            field=models.CharField(default='read', max_length=20),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
